# This file is a ROS 2 launch parameter file. For more information, see:
# https://docs.ros.org/en/humble/Tutorials/Intermediate/Launch/Using-ROS2-Launch-For-Large-Projects.html

controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    action_ns: follow_joint_trajectory
    joints:
      - shoulder_pan
      - shoulder_lift
      - elbow_flex
      - wrist_roll
      - wrist_pitch
      - wrist_yaw

gripper_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    action_ns: follow_joint_trajectory
    joints:
      - gripper_jaw