generated: '2025-10-21T13:22:53.913277'
shoulder_pan:
  range_min: 423
  range_max: 2706
  homing_offset: 1564
shoulder_lift:
  range_min: 868
  range_max: 3071
  homing_offset: 1969
elbow_flex:
  range_min: 892
  range_max: 3021
  homing_offset: 1956
wrist_flex:
  range_min: 915
  range_max: 3108
  homing_offset: 2011
wrist_roll:
  range_min: 377
  range_max: 2479
  homing_offset: 1428
gripper:
  range_min: 1043
  range_max: 1754
  homing_offset: 1188